targets:
  $default:
    builders:
      box_generator|box:
        enabled: true

builders:
  box_generator:
    target: ":box_generator"
    import: "package:box_generator/box_registry_builder.dart"
    builder_factories: ["registryBuilder"]
    build_extensions: {".dart": [".box_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
