name: box_generator
homepage: https://github.com/stijnvanbael/box_generator
description: Registry generator for Box, a fluent Dart persistence API inspired by SQL.
version: 0.3.3+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.2
  source_gen: ^1.0.2
  box: #^0.3.3+1
    path: ../box
  analyzer: ^1.7.1

dev_dependencies:
  build_test: ^2.1.0
  build_runner: ^2.0.4
  test: ^1.17.8
