name: box_generator
homepage: https://github.com/stijnvanbael/box_generator
description: Registry generator for Box, a fluent Dart persistence API inspired by SQL.
version: 0.3.0+1

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  build: ^1.5.0
  source_gen: ^0.9.8
  box: ^0.3.0+2
  analyzer: ^0.40.5

dev_dependencies:
  build_test: ^1.0.0
  build_runner: ^1.8.0
  test: ^1.10.0
