name: box_generator
homepage: https://github.com/stijnvanbael/box_generator
description: Registry generator for Box, a fluent Dart persistence API inspired by SQL.
version: 0.3.3+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  box: ^0.3.3+2
  analyzer: ^2.7.0

dev_dependencies:
  lints: ^1.0.0
  build_test: ^2.1.0
  build_runner: ^2.0.4
  test: ^1.17.8
