name: box_generator
homepage: https://github.com/stijnvanbael/box_generator
description: A registry generator for using Box without mirrors
version: 0.2.6

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.5
  box: ^0.2.6
  analyzer: ^0.39.10

dev_dependencies:
  build_test: ^1.0.0
  build_runner: ^1.8.0
  test: ^1.10.0
