name: box_generator
homepage: https://github.com/stijnvanbael/box_generator
description: Registry generator for Box, a fluent Dart persistence API inspired by SQL.
version: 0.4.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.1
  source_gen: ^1.4.0
  box:
    path: ../box
  analyzer: ^6.2.0

dev_dependencies:
  lints: ^2.1.1
  build_test: ^2.2.0
  build_runner: ^2.4.6
  test: ^1.24.6